version: '3'
services:
  cms:    
    build:
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./cms/uploads:/var/www/html/cms/wp-content/uploads
    links:
      - cmsdb:cmsdb
    container_name: cms
  cmsdb:
    image: mysql:latest
    ports:
      - '13307:3306'
    volumes:
      - ./cmsdb/data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secrets
      MYSQL_DATABASE: cms_db
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: secrets
    container_name: cmsdb
