version: '2'
services:
  cms:
    build: ./cms
    ports:
      - '8080:80'
    volumes:
      - ../themes/portfolio:/var/www/html/cms/wp-content/themes/portfolio
      - ../themes/img:/var/www/html/img
    links:
      - cmsdb:cmsdb
    container_name: cms
  cmsdb:
    build: ./cmsdb
    ports:
      - '13307:3306'
    volumes:
      - ./cmsdb/data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secrets
      MYSQL_DATABASE: cms_db
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: secrets
    container_name: cmsdb
